/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChartComponent: typeof import('./src/components/registry/chart/BarChartComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/registry/basic/ButtonComponent.vue')['default']
    CardGroupComponent: typeof import('./src/components/registry/container/CardGroupComponent.vue')['default']
    ContainerComponent: typeof import('./src/components/registry/container/ContainerComponent.vue')['default']
    DatePickerComponent: typeof import('./src/components/registry/form/DatePickerComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FormComponent: typeof import('./src/components/registry/container/FormComponent.vue')['default']
    ImageComponent: typeof import('./src/components/registry/basic/ImageComponent.vue')['default']
    InputComponent: typeof import('./src/components/registry/form/InputComponent.vue')['default']
    LineChartComponent: typeof import('./src/components/registry/chart/LineChartComponent.vue')['default']
    ModalComponent: typeof import('./src/components/registry/advanced/ModalComponent.vue')['default']
    RenderNode: typeof import('./src/components/registry/RenderNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectComponent: typeof import('./src/components/registry/form/SelectComponent.vue')['default']
    TableComponent: typeof import('./src/components/registry/data/TableComponent.vue')['default']
    TabsComponent: typeof import('./src/components/registry/container/TabsComponent.vue')['default']
    TextComponent: typeof import('./src/components/registry/basic/TextComponent.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UploadComponent: typeof import('./src/components/registry/form/UploadComponent.vue')['default']
  }
}
